# Generated by Django 4.1.5 on 2023-01-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_profile_phoneno_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="username",
        ),
    ]
