# Generated by Django 4.1.5 on 2023-01-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_remove_friend_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friends",
            field=models.ManyToManyField(
                related_name="user_friends", to="base.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Friend",
        ),
    ]
