# Generated by Django 4.1.5 on 2023-01-06 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_profile_friends_delete_friend"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.profile",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="paidBy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_by",
                to="base.profile",
            ),
        ),
    ]
