# Generated by Django 4.1.5 on 2023-01-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_transaction_participants_participant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="participants",
        ),
    ]
