# Generated by Django 4.1.5 on 2023-01-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_participant_participant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="isPaid",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
