# Generated by Django 4.1.5 on 2023-01-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_participant_ispaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="participants",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
