# Generated by Django 4.1.5 on 2023-01-07 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_transaction_participants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Participant",
        ),
    ]
