# Generated by Django 4.1.5 on 2023-01-07 03:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_remove_profile_friends_friend"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="participants",
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "createdAt",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "amountOwes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("isPaid", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="particpant_owner",
                        to="base.profile",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_transaction",
                        to="base.transaction",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner", "transaction")},
            },
        ),
    ]
