# Generated by Django 4.1.5 on 2023-01-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_remove_transaction_splittype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("clothing", "clothing"),
                    ("food", "food"),
                    ("entertainment", "entertainment"),
                    ("travel", "travel"),
                    ("none", "none"),
                ],
                default="none",
                max_length=200,
            ),
        ),
    ]
