# Generated by Django 4.1.5 on 2023-01-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transactionType",
            field=models.CharField(
                choices=[
                    ("split equally", "split equally"),
                    ("treat", "treat"),
                    ("custom split", "custom split"),
                    ("one-time", "one-time"),
                    ("none", "none"),
                ],
                default="none",
                max_length=200,
            ),
        ),
    ]
